### ISSUE TITLE
Бета ТЗ и альфа ИЧ РПЗ | Спринт 19.09.2018

### ISSUE THREAD

**Issue by Accvad** [Accvad/Lighthouse#3]
Дописать альфу ТЗ до беты и написать исследовательскую часть РПЗ

**Comment by Accvad** [comment]
Бета версия технического задания. Замечания были исправлены.
[LighthouseProjectTT.docx](https://github.com/Accvad/Lighthouse/files/2394770/LighthouseProjectTT.docx)

Мега альфа версия исследовательской части.
[LighthouseProjectRPZ.docx](https://github.com/Accvad/Lighthouse/files/2394776/LighthouseProjectRPZ.docx)

**Comment by wldmr-key** [comment]
Техническое задание:

ПАДЕЖИ и ЧИСЛА!!!

> 3.1. Краткие сведения об объекте автоматизации
> Пользователь при помощи фильтров может искать интересующие его медиа, затем он может добавить его в список желаемого, чтобы посмотреть позже, либо сразу добавляет его в список законченного с добавлением простого отзыва и комментария к продукту. Также будет предусмотрено оповещение пользователя о новом продукте автора на которого он может подписан. Использование бота в месседжере Telegram позволяет воспользоваться сервисом как с помощью десктопного приложения или веб-версии, так и с помощью приложения для смартфона на Android или iOS.
> 

Так кто на ком стоит? (С) Где находятся медиа? что за списки желаемого и законченного и как люди со всем этим жили до сих пор без твоего бота? Нужно описание доступное для обычного человека - это не пойдет

Требования к функциям - аналогично. Либо они должны быть самодостаточны, либо следовать из предыдущего пункта

Где предполагается хостинг БД?

**Comment by Accvad** [comment]
Косяки падежей и чисел учту :), но не совсем понял про требования к функциям. Имеется в виду, что весь функционал из краткого сведения должен быть перефразирован в требованиях к функциям (ну и оформлен в виде списка)? 

Хостинг БД будет на моем компьютере как и сам бот если я вас правильно понял. Про это нужно написать в кратких сведениях? 

И еще, возможен ли копипаст в исследовательской части

**Comment by wldmr-key** [comment]
> Имеется в виду, что весь функционал из краткого сведения должен быть перефразирован в требованиях к функциям (ну и оформлен в виде списка)?

имеется в виду, что функции должны быть понятны

> Про это нужно написать в кратких сведениях?

можно написать, что хостинг будет на специализированном сервере. К нему никаких требований нет? (по софту, как минимум)

> И еще, возможен ли копипаст в исследовательской части

куда ж вы без него? )) только авторство не забывай указывать

**Comment by Accvad** [comment]
>К нему никаких требований нет? (по софту, как минимум)
Из требований можно сказать что нужна установка языка программирования, достаточное количество памяти для хранения данных и настройка сети.

> куда ж вы без него? )) только авторство не забывай указывать
Да не, копипаст текста из ТЗ :D

**Comment by Accvad** [comment]
Следующий спринт здесь https://github.com/Accvad/Lighthouse/issues/4
