### ISSUE TITLE
Приближение к 25% | Спринт 25.09.2018

### ISSUE THREAD

**Issue by Accvad** [Accvad/Lighthouse#4]
- [x] Составить пре-релиз ТЗ

- [x] Составить альфу-версию схемы базы данных

- [x] Составить бета-версию Исследовательской части

**Comment by Accvad** [comment]
[LighthouseProjectTT.docx](https://github.com/Accvad/Lighthouse/files/2417040/LighthouseProjectTT.docx)

**Comment by Accvad** [comment]
Схема базы данных
https://drive.google.com/file/d/1XpdDJMW98-q7EQX2WchkdrLZFvOdOcPb/view?usp=sharing

**Comment by Accvad** [comment]
Мало обосновал использование Postgres, нужно будет дописать. 
[LighthouseProjectRPZ.docx](https://github.com/Accvad/Lighthouse/files/2417503/LighthouseProjectRPZ.docx)

**Comment by Accvad** [comment]
Появились несколько вопросов по базе данных, которые я хочу спросить непосредственно на паре.

**Comment by wldmr-key** [comment]
Раз, уж, все документы появились одной кучей, отвечаю на все сразу
**ТЗ**
цель: зачем нужно "собрание в одном месте"?
Объектом автоматизации являются действия меломана. Какие у него возникают проблемы без твоей системы? Какие из этих проблем можно решить автоматизированно? Ты отвечаешь только на второй вопрос
База данных хранит в себе фильмы или ссылки на фильмы? (судя по структуре БД - ни то, ни другое)

**Описание предметной области**
Копипаст функций из ТЗ здесь уже не прокатывает. Нужно описывать понятия и процессы. Что это за список желаемого? Как он формируется? Что это за возможность находить? Если я хочу фильм про кошечек, я его найду?
Концептуальная схема БД так не рисуется - имеет смысл прочитать методичку и, возможно, лекции или другую полезную литературу.
Перечитай перечень задач: это, действительно, то что ты собираешься делать по результатам исследования?
Обоснование выбора - это перечисление аргументов "за". Я не увидел ни одного...

**Comment by Accvad** [comment]
Понял, тогда на паре спрошу пару вопросов и попробую наверстать упущенное в ближайшие дни.

**Comment by Accvad** [comment]
Следующий спринт https://github.com/Accvad/Lighthouse/issues/5
