### ISSUE TITLE
Исследовательская часть | Спринт 01.10.2018

### ISSUE THREAD

**Issue by Accvad** [Accvad/Lighthouse#5]
- [x] Переписать постановку задачи проектирования

- [ ] Дописать описание предметной области

- [x] Составить перечень задач, подлежащих решению в процессе разработки.

- [x] Обосновать выбор инструмента и платформы для разработки

- [x] Починить техническое задание

**Comment by Accvad** [comment]
[LighthouseProjectTT.docx](https://github.com/Accvad/Lighthouse/files/2439876/LighthouseProjectTT.docx)

ТЗ:
2.2	Незначительно изменено. Не уверен в правильности. Возможно стоит полностью переписать
3.1	Нужно ли полностью переписать этот пункт? Не могу придумать как ответить на вопрос "Какие у него возникают проблемы без твоей системы?" без изменения всего пункта.

[LighthouseProjectRPZ.docx](https://github.com/Accvad/Lighthouse/files/2439878/LighthouseProjectRPZ.docx)

РПЗ:
1	Переписан полностью
2.1 	Переписан полностью
2.2	Не уверен в надобности наличия этого пункта
2.3	Очень не уверен в правильности схемы. Описание рисунка не дописано. Правильно ли хранить в одной таблице (например законченного) добавления каждого пользователя как в лабах с краской(история покрасок). Мне кажется это можно сделать правильнее и оптимизированее, но я не могу придумать как. 
2.4	Аналогично что и в тз. Нужно ли перефразировать?
3	Не понял в чем проблема. Незначительно изменен
4	Очень не уверен в правильности. 
Итог: Исследовательская часть еще не дописана. Нужно добавить сценарий использования.

**Comment by wldmr-key** [comment]
резюме по ТЗ - оставляй как есть
По РПЗ - все стало значительно лучше, но остались вопросы:
2.1.
**в заранее созданной базе данных ** - кем созданной (вне системы?)? где хранимой? как изменяемой?
**он может оставить заявку на добавление отсутствующего медиа в базу данных** - ему легче от этого станет? Что с этой заявкой происходит потом?
**некоторое количество баллов за просмотр. За определенное количество баллов дается уровень** - то есть, "некоторое" и "определенное" - это случайные числа? Или есть какие-то правила? Они секретные?
**подписаться на авторов продуктов** - это кто?

2.2. Возможность - плохое слово для описания функций.
Этот пункт нужен.
Функций не хватает - как происходит изменение базы медиаресурсов и исполнение желаний пользователей. Что там с баллам и кармой?

2.3 Во-первых, так ER-диаграммы не рисуют (см. методичку что-ли). Твой вопрос некорректен - говоря о сущностях мы еще не имеем в виду никаких таблиц. Если у тебя нарисована стрелка (связь) пользователя со списком, то атрибут "имя пользователя" непонятен абсолютно. Чтобы все сделать правильнее почитай про концептуальные схемы и ER-модель
2.4 можно не писать, просто
3. ТЗ уже есть. Второй раз составлять не нужно...
4. Ты уверен, что все преимущества постгреса, которые ты перечислил, тебе нужны?

**Comment by Accvad** [comment]
Следующий спринт здесь: https://github.com/Accvad/Lighthouse/issues/6

**Comment by Accvad** [comment]
Следующий спринт здесь https://github.com/Accvad/Lighthouse/issues/6

**Comment by Accvad** [comment]
Закрываю из-за смены ведения github
